version: "2"
services:
  app:
    build: ./
    command:
      [
        sh,
        -c,
        "cd /app/server && yarn run watch-server & cd /app/spa && yarn run
          start"
      ]
    environment:
      - DROPBOX_APP_KEY=${DROPBOX_APP_KEY}
      - DROPBOX_APP_SECRET=${DROPBOX_APP_SECRET}
      - JWT_COOKIE_SECRET=${JWT_COOKIE_SECRET}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_DATABASE_TESTING=${MYSQL_DATABASE_TESTING}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - NODE_ENV=development
      - LOG_LEVEL=info
      - IMAGGA_KEY=${IMAGGA_KEY}
      - IMAGGA_SECRET=${IMAGGA_SECRET}
      - API_LOCATION_IQ_KEY=${API_LOCATION_IQ_KEY}
      - API_GOOGLE_ELEVATION_KEY=${API_GOOGLE_ELEVATION_KEY}
      - API_OCR_SPACE_KEY=${API_OCR_SPACE_KEY}
      - API_PLATE_RECOGNIZER=${API_PLATE_RECOGNIZER}
      - API_PLANT_NET_KEY=${API_PLANT_NET_KEY}
      - SEARCH_CONFIDENCE_THRESHOLD=${SEARCH_CONFIDENCE_THRESHOLD}
      - SPA_EXTERNAL_PORT=3500
      - API_EXTERNAL_PORT=3501
      - API_INTERNAL_PORT=4000
      - API_HOST=localhost
      - SPA_HOST=localhost
    ports:
      - "3500:3000"
      - "3501:4000"
      - "9229:9229"
    volumes:
      - ./app:/app
    expose:
      - "3500"
      - "3501"
      - "9229"
    depends_on:
      - mysql
      # only in dev do we need phpmyadmin (so we can just bash into the server and stil use mysql/phpmyadmin)
      - phpmyadmin

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_ARBITRARY=1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - UPLOAD_LIMIT=2G
    ports:
      - "8083:80"
    expose:
      - "80"
    volumes:
      - /sessions
    depends_on:
      - mysql

volumes:
  mysqldata:
    driver: "local"
