version: "2"
services:
  app:
      build: ./
      # command: [sh, -c, "cd /app/server && yarn run watch-server & cd /app/spa && yarn run start"]
      command: [sh, -c, "cd /app/spa && yarn run start"]
      ports:
        - "3500:3000"
        - "3501:4000"
      volumes:
        - ./app:/app
      expose:
        - "3500"
        - "3501"
