
export enum TaskType {
    DROPBOX_SYNC = 'DROPBOX_SYNC',
    DROPBOX_FILE_IMPORT = 'DROPBOX_FILE_IMPORT',
    PHYSICAL_FILE = 'PHYSICAL_FILE',
    REMOVE_FILE = 'REMOVE_FILE',
    ADDRESS_LOOKUP = 'ADDRESS_LOOKUP',
    ELEVATION_LOOKUP = 'ELEVATION_LOOKUP',
    PLANT_LOOKUP = 'PLANT_LOOKUP',
    OCR_GENERIC = 'OCR_GENERIC',
    OCR_NUMBERPLATE = 'OCR_NUMBERPLATE',
    SUBJECT_DETECTION = 'SUBJECT_DETECTION',
}
