
export enum TaskType {
    DROPBOX_SYNC = 'DROPBOX_SYNC',
    DROPBOX_FILE_IMPORT = 'DROPBOX_FILE_IMPORT',
    PROCESS_IMAGE_FILE = 'PROCESS_IMAGE_FILE',
    PROCESS_VIDEO_FILE = 'PROCESS_VIDEO_FILE',
    REMOVE_PROCESSING_FILE = 'REMOVE_PROCESSING_FILE',
    ADDRESS_LOOKUP = 'ADDRESS_LOOKUP',
    ELEVATION_LOOKUP = 'ELEVATION_LOOKUP',
    PLANT_LOOKUP = 'PLANT_LOOKUP',
    OCR_GENERIC = 'OCR_GENERIC',
    OCR_NUMBERPLATE = 'OCR_NUMBERPLATE',
    SUBJECT_DETECTION = 'SUBJECT_DETECTION',
    REMOVE_FILE = 'REMOVE_FILE',
}

export enum FileType {
    IMAGE = 'IMAGE',
    VIDEO = 'VIDEO'
}